export const ADD_PRODUCT='ADD_PRODUCT'
export const DELETE_PRODUCT='DELETE_PRODUCT';
export const EDIT_PRODUCT='EDIT_PRODUCT';
export const CHANHGE_QTE='CHANHGE_QTE';
export const ADD_CART='ADD_CART';
export const DELETE_CART='DELETE_CART';